version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  product-service:
    image: va4815/k8s-product-service:0.0.2
    build:
      context: .
    container_name: k8s-product-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

