server.port=8080
spring.config.import=optional:file:.env.docker[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:productdb}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
